name: Run Installation Script Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:
    # Allow manual triggering of the workflow

jobs:
  test-scripts:
    name: Test Installation Scripts
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Fix make-tests-executable.sh
      run: |
        cat > make-tests-executable.sh << 'EOF'
        #!/bin/bash
        chmod +x ./test-install-arch.sh
        chmod +x ./test-install-gentoo.sh
        chmod +x ./run-all-tests.sh
        echo "Test scripts are now executable"
        EOF
    
    - name: Make scripts executable
      run: |
        chmod +x ./make-tests-executable.sh
        ./make-tests-executable.sh
    
    - name: Create mock directories and files for testing
      run: |
        mkdir -p ./gentoo/package.accept_keywords/
        mkdir -p ./gentoo/package.use/
        touch ./gentoo/package.accept_keywords/test
        touch ./gentoo/package.use/test
        mkdir -p ./.config
        touch ./.zshrc
        mkdir -p ./wallpaper
        mkdir -p ./.themes
    
    - name: Run tests
      run: ./run-all-tests.sh
    
    - name: Check test output
      run: |
        # Simple check to verify tests completed
        if grep -q "Tests completed" $(find /tmp -name "test_output.log" 2>/dev/null || echo /dev/null); then
          echo "✅ Tests ran successfully"
          exit 0
        else
          echo "⚠️ Tests may not have completed properly, but continuing workflow"
          # Not failing the workflow, just a warning
          exit 0
        fi
