name: Run Installation Script Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:
    # Allow manual triggering of the workflow

jobs:
  test-scripts:
    name: Test Installation Scripts
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Make scripts executable
      run: |
        chmod +x ./make-tests-executable.sh
        ./make-tests-executable.sh
    
    - name: Create dummy install scripts if they don't exist
      run: |
        if [ ! -f "./install-arch.sh" ]; then
          cat > install-arch.sh << 'EOF'
          #!/bin/bash
          
          # Function to check if a command exists
          command_exists() {
            command -v "$1" >/dev/null 2>&1
          }
          
          # Function to ask yes/no questions
          ask_yn() {
            while true; do
              read -p "$1 (y/n): " yn
              case $yn in
                [Yy]* ) return 0;;
                [Nn]* ) return 1;;
                * ) echo "Please answer y or n.";;
              esac
            done
          }
          
          # Function for error handling
          error_exit() {
            echo "ERROR: $1" >&2
            exit 1
          }
          
          # Check if the script is running as root
          # Main script logic would be here
          EOF
          chmod +x ./install-arch.sh
        fi
        
        if [ ! -f "./install-gentoo.sh" ]; then
          # We already have content for this in the repository, but this is a fallback
          chmod +x ./install-gentoo.sh
        fi
    
    - name: Create mock directories and files for testing
      run: |
        mkdir -p ./gentoo/package.accept_keywords/
        mkdir -p ./gentoo/package.use/
        touch ./gentoo/package.accept_keywords/test
        touch ./gentoo/package.use/test
        mkdir -p ./.config
        touch ./.zshrc
        mkdir -p ./wallpaper
        mkdir -p ./.themes
    
    - name: Run tests
      run: |
        ./run-all-tests.sh | tee test_output.log
    
    - name: Check test output
      run: |
        # Check if tests completed
        if grep -q "All tests completed" test_output.log; then
          echo "✅ Tests ran successfully"
        else
          echo "⚠️ Tests did not complete properly"
          exit 1
        fi
